name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  flutter_build:
    name: Flutter build
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v3

      # Installing Flutter because it's easier to generate .lcov files for test coverage
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.8'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Check build
        run: flutter analyze

  phoenix_build:
    name: Phoenix build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.14.2' # Define the elixir version [required]
        otp-version: '25.1.2' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix coveralls.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MIX_ENV: test